replicaCount: 2

image:
  repository: ghcr.io/vijaymahes9080/greenagent-os
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: greenagent.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

env:
  ENVIRONMENT: production
  DATACENTER_PUE: 1.25
  DEFAULT_REGION: us-east
